name: CI WORKFLOW DEV
on: [push , pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install go
        uses: apt install golang@1.22

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'
        
      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build -o giftcard